blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, change_post_status, HomeListView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('home/', HomeListView.as_view(), name='home'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('change_post_status/<int:pk>/', change_post_status, name='change_post_status'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    # path('', home, name='home'),
    # path('home2/', home2, name='home2'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('client/', ClientListView.as_view(), name='client'),
    path('settings/', SettingsListView.as_view(), name='settings'),
    path('create_settings/', SettingsCreateView.as_view(), name='create_settings'),
    path('update_settings/<int:pk>/', SettingsUpdateView.as_view(), name='update_settings'),
    path('delete_settings/<int:pk>/', SettingsDeleteView.as_view(), name='delete_settings'),
    path('detail_settings/<int:pk>/', SettingsDetailView.as_view(), name='detail_settings'),
    path('message/', MessageListView.as_view(), name='message'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('detail_message/<int:pk>/', MessageDetailView.as_view(), name='detail_message'),
    path('status/', Send_messageListView.as_view(), name='status'),
    path('delete_status/<int:pk>/', Send_messageDeleteView.as_view(), name='delete_status'),
    path('change_status_settings/<int:pk>/', change_status_settings, name='change_status_settings'),


]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import CustomLoginView, CustomRegisterView, UserEditProfileView, CustomPasswordChangeView, \
    activate_user, page_after_registration, CustomPasswordResetView, CustomPasswordResetConfirmView, \
    password_reset_send_mail, CustomPasswordResetCompleteView, UserListView, change_user_status

app_name = UsersConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(extra_context='/blog/home'), name='logout'),
    path('registration/', CustomRegisterView.as_view(), name='registration'),
    path('page_after_registration/<str:token>/', page_after_registration, name='page_after_registration'),
    path('profile/', UserEditProfileView.as_view(), name='profile'),
    path('password/', CustomPasswordChangeView.as_view(), name='password'), # пытался сделать урл change_password, но что-то как-то сложно...
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_send_mail/', password_reset_send_mail, name='password_reset_send_mail'),
    path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('activate/<str:token>/', activate_user, name='activate'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('status/<int:pk>/', change_user_status, name='status'),
    # path('repeat_message/<str:token>/', repeat_message, name='repeat_message'),
    # path('reset_password/', ..., name='reset_password'),

]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}

class Client(models.Model):

    email = models.EmailField(max_length=60, verbose_name='Email')
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(blank=True, verbose_name='Комментарий')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

    def __str__(self):
        return f'{self.email} {self.fio}'


class Message(models.Model):

    title = models.CharField(max_length=80, verbose_name='Тема письма')
    text = models.TextField(verbose_name='Тело письма')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'

    def __str__(self):
        return f'{self.title}'


class Settings(models.Model):
    FREQUENCY = (
        ('day', 'раз в день'),
        ('week', 'раз в неделю'),
        ('month', 'раз в месяц'),
    )
    FREQUENCY_DAY = 'day'
    FREQUENCY_WEEK = 'week'
    FREQUENCY_MONTH = 'month'

    STATUS = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
    )
    STATUS_COMPLETED = 'completed'
    STATUS_CREATED = 'created'
    STATUS_LAUNCHED = 'launched'

    mailing_time = models.TimeField(verbose_name='Время рассылки')
    frequency = models.CharField(max_length=25, default=FREQUENCY_DAY, choices=FREQUENCY, verbose_name='Периодичность')
    status = models.CharField(max_length=25, default=STATUS_CREATED, choices=STATUS, verbose_name='Статус')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')

    addressee = models.ManyToManyField(Client, verbose_name='Адреса')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    class Meta:
        verbose_name = 'настройки'
        verbose_name_plural = 'настройки'

        permissions = [
            (
                'change_status_settings',
                'Can change the status settings'
            ),

        ]

    def __str__(self):
        return f'{self.mailing_time}, {self.frequency}'


class Send_message(models.Model):
    STATUS = (
        ('delivered', 'доставлено'),
        ('not_delivered', 'не доставлено'),
    )
    STATUS_DELIVERED = 'delivered'
    STATUS_NOT_DELIVERED = 'not_delivered'

    sending_time = models.DateTimeField(verbose_name='Время рассылки')
    status = models.CharField(max_length=25, default=STATUS_DELIVERED, choices=STATUS, verbose_name='Статус')
    server_response = models.CharField(blank=True, max_length=100, verbose_name='Ответ сервера')

    settings_pk = models.ForeignKey(Settings, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)


    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытка рассылки'

    def __str__(self):
        return f'{self.sending_time} {self.status} {self.server_response} '

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='почта', unique=True)
    phone = models.CharField(max_length=25, verbose_name='номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=15, verbose_name='токен')
    token_time = models.DateTimeField(auto_now_add=True, verbose_name='время создания токена')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            (
                'change_status_user',
                'Can change the status user'
            ),


        ]

mailing/forms.py
from django import forms

from mailing.forms_mixins import StyleFormMixin
from mailing.models import Client, Message, Settings


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('owner',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ('title', 'text',)
        exclude = ('owner',)


class SettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Settings
        fields = ('mailing_time', 'frequency', 'status', 'message', 'addressee')
        exclude = ('owner',)

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop('owner')
        super().__init__(*args, **kwargs)

        self.fields['addressee'].queryset = Client.objects.filter(owner=owner)
        self.fields['message'].queryset = Message.objects.filter(owner=owner)

mailing/views.py
import random

from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import *

from blog.models import Blog
from mailing.forms import ClientForm, MessageForm, SettingsForm
from mailing.models import *
from django.urls import reverse_lazy

# def home(request):
#     blog = Blog.objects.filter(publication_status=Blog.STATUS_ACTIVE)
#     blog_id = [item[0] for item in blog.values_list('id')]
#     random.shuffle(blog_id)
#     number_publication = 3
#
#     if len(blog_id) < 3:
#         number_publication = len(blog_id)
#
#     return render(request, 'mailing/home_page.html', {'blog':[blog.filter(id=blog_id[n]) for n in range(number_publication)]})


class ClientListView(UserPassesTestMixin, ListView):
    model = Client
    template_name = 'mailing/client/client_list.html'

    def test_func(self):
        return self.request.user.is_authenticated



class ClientCreateView(UserPassesTestMixin, CreateView):
    model = Client
    success_url = reverse_lazy('mailing:client')
    template_name = 'mailing/client/client_form.html'
    form_class = ClientForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(ClientCreateView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated

class ClientUpdateView(UserPassesTestMixin, UpdateView):
    model = Client
    success_url = reverse_lazy('mailing:client')
    template_name = 'mailing/client/client_form.html'
    form_class = ClientForm

    def test_func(self):
        client = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == client.owner

class ClientDeleteView(UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client')
    template_name = 'mailing/client/client_confirm_delete.html'

    def test_func(self):
        client = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == client.owner


class SettingsListView(UserPassesTestMixin, ListView):
    model = Settings
    template_name = 'mailing/settings/settings_list.html'

    def test_func(self):
        return self.request.user.is_authenticated

class SettingsCreateView(UserPassesTestMixin, CreateView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_form.html'
    form_class = SettingsForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(SettingsCreateView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'owner':self.request.user})
        return kwargs

class SettingsUpdateView(UserPassesTestMixin, UpdateView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_form.html'
    form_class = SettingsForm

    def test_func(self):
        settings = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == settings.owner

class SettingsDeleteView(UserPassesTestMixin, DeleteView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_confirm_delete.html'

    def test_func(self):
        settings = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == settings.owner

class SettingsDetailView(UserPassesTestMixin, DetailView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_detail.html'

    def test_func(self):
        message = self.get_object()
        if self.request.user == message.owner:
            return True
        return self.request.user.has_perm('mailing.view_settings')


class MessageListView(UserPassesTestMixin, ListView):
    model = Message
    template_name = 'mailing/message/message_list.html'

    def test_func(self):
        return self.request.user.is_authenticated

class MessageCreateView(UserPassesTestMixin, CreateView):
    model = Message
    success_url = reverse_lazy('mailing:message')
    template_name = 'mailing/message/message_form.html'
    form_class = MessageForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(MessageCreateView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated

class MessageUpdateView(UserPassesTestMixin, UpdateView):
    model = Message
    success_url = reverse_lazy('mailing:message')
    template_name = 'mailing/message/message_form.html'
    form_class = MessageForm

    def test_func(self):
        message = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == message.owner

class MessageDeleteView(UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message')
    template_name = 'mailing/message/message_confirm_delete.html'

    def test_func(self):
        message = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == message.owner

class MessageDetailView(UserPassesTestMixin, DetailView):
    model = Message
    template_name = 'mailing/message/message_detail.html'

    def test_func(self):
        message = self.get_object()
        if self.request.user == message.owner:
            return True
        return self.request.user.has_perm('mailing.view_message')


class Send_messageListView(UserPassesTestMixin, ListView):
    model = Send_message
    template_name = 'mailing/send/send_message_list.html'

    def test_func(self):
        return self.request.user.is_authenticated

class Send_messageDeleteView(UserPassesTestMixin, DeleteView):
    model = Send_message
    success_url = reverse_lazy('mailing:status')
    template_name = 'mailing/send/send_message_confirm_delete.html'

    def test_func(self):
        return self.request.user.is_superuser


def change_status_settings(request, pk):
    """Смена статуса настройки"""
    obj = get_object_or_404(Settings, pk=pk)
    if obj.status == Settings.STATUS_COMPLETED or obj.status == Settings.STATUS_CREATED:
        obj.status = Settings.STATUS_LAUNCHED
    elif obj.status == Settings.STATUS_LAUNCHED:
        obj.status = Settings.STATUS_COMPLETED
    obj.save()

    return redirect(request.META.get('HTTP_REFERER'))

mailing/templates/mailing/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сервис рассылок "Спам и точка"</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <h2 class="">Спам и точка</h2>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'blog:home' %}" class="nav-link px-2 text-secondary">Главная</a></li>
                <li><a href="{% url 'blog:list' %}" class="nav-link px-2 text-secondary">Блог</a></li>
                <li><a href="{% url 'mailing:message' %}" class="nav-link px-2 text-white">Настроить рассылку</a></li>
                <li><a href="{% url 'mailing:client' %}" class="nav-link px-2 text-white">База пользователей</a></li>
                <li><a href="{% url 'mailing:status' %}" class="nav-link px-2 text-white">Статус рассылки</a></li>
                {% if perms.users.view_user %}
                <li><a href="{% url 'users:users_list' %}" class="nav-link px-2 text-white">Список аккаунтов</a></li>
                {% endif %}
            </ul>

            <div class="text-end">
                {% if user.is_authenticated %}
                <a href="{% url 'users:profile' %}" class="btn btn-outline-light me-2">Профиль</a>
                <a href="{% url 'users:logout' %}" class="btn btn-outline-light me-2">Выход</a>

                    {% else %}
                    <a href="{% url 'users:login' %}" class="btn btn-outline-light me-2">Вход</a>
                <a href="{% url 'users:registration' %}" class="btn btn-warning">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

<body style="background-image: url(/static/image/0dae2f5a78b5177a4ca2c81185345206.jpg)">
<div class="wrapper">


    {% block home %}
    {% endblock %}
    {% block content %}
    {% endblock %}

    {% block client_create %}
    {% endblock %}
    {% block client_delete %}
    {% endblock %}
    {% block client %}
    {% endblock %}

    {% block settings %}
    {% endblock %}
    {% block settings_create %}
    {% endblock %}
    {% block detail_settings %}
    {% endblock %}

    {% block message %}
    {% endblock %}
    {% block message_create %}
    {% endblock %}
    {% block message_delete %}
    {% endblock %}
    {% block detail_message %}
    {% endblock %}

    {% block status %}
    {% endblock %}
    {% block status_delete %}
    {% endblock %}

    <script src="/static/js/bootstrap.bundle.js"></script>
</body>

</div>


<footer class="footer">
    <div class="p-3 text-bg-secondary">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

                <div class="col-md">
                    Спам и точка
                    <small class="d-block mb-3 ">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-light" href="#">Контакты</a></li>
                        <li><a class="text-light" href="https://shewzov.ru/developers/privacy-policy">Политика
                            конфиденциальности</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    <style>
        body {
            min-height: 100vh;
            display: flex;
            flex-direction: column;
        }

        footer {
            margin-top: auto;
        }
    </style>

</footer>

mailing/templates/mailing/home_page.html
{% extends 'mailing/base.html' %}

{% load mailing_count %}
{% load users_count %}
{% block home %}

    <div class="container-xl">
    <br>
        <div class="row">
            <div class="col-3 ">
                <img src="/static/image/1639479823_3-pofoto-club-p-pochtovii-golub-ptitsi-foto-3.jpg" width="100%"/>
            </div>
            <div class="col-9">
                <div>
                    <p class="lead">
                    </p>
                </div>
                <p class="lead">
                    <font size="4" color="#472929" face="sans-serif">
                         ***************************************************************<br><br>
                        - самая быстрая почта на диком западе<br><br>
                        - высокие показатели открытия и прочтения сообщений<br><br>
                        - кэшбэки до 7%<br><br>

                    ***************************************************************
                </p>
            </div>
        </div>
        <div style="content">

            <p>
                <br>
                <br>
                <font size="4" color="#472929" face="sans-serif">
                Наши серверы расположены в нескольких надежных дата-центрах на территории РФ, а все программное
                обеспечение сервиса является российским.
                <br>Мы можем смело заявить, что в соответствии с государственной политикой импортозамещения, "Спам и
                точка" является полным аналогом зарубежных платформ.
                <br>Тарифы "Спам и точка" не привязаны к валютам и рассчитываются исключительно в рублях. Цены на услуги
                не будут меняться в ближайшее время.
            </p>
            <br>
        </div>
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col">
                    <div class="card shadow-sm text-center" style="background: #e0e0e0">
                        <figure class="p-3 mb-0">
                            Через наш сайт было создано {% mailing_count %}.<br>
                            <br>
                            На данный момент запущен{% active_mailing_count %}.
                        </figure>
                    </div>
                </div>
                <div class="col">
                    <div class="" >

                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm text-center" style="background: #e0e0e0">
                        <figure class="p-3 mb-0">
                            Сервисом "Спам и точка" пользуются {% user_count %}.<br>
                            <br>
                            Через наш сервис охватили {% client_count %}.
                        </figure>
                    </div>
                </div>
            </div>
        </div>
        <br>
        <div class="text-center">
            <h1 class="display-4"> Читайте наш блог: </h1>
        </div>
        <br>

    <div class="container">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for publication in cache_home_page %}
                <div class="col">
                <div class="card shadow-sm" style="background: #e0e0e0">
                    <img class="bd-placeholder-img card-img-top" width="100%" height="225"
                         src="/media/{{ publication.first.image_preview }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ publication.first.header|capfirst }}</h5>
                        <p class="card-text">{{ publication.first.content|slice:":80"|capfirst }}...</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group col-3">
                                <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'blog:detail' publication.first.pk %}">Читать</a>
                            </div>
                            <small class="text-muted">{{ publication.first.date_created|date }}</small>
                        </div>
                    </div>
                </div>
            </div>
                <br>
            {% endfor %}
        </div>
    </div>
    <br>
    </div>







    <div style="clear: both;"></div>






{% endblock %}