blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, change_post_status, HomeListView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('home/', HomeListView.as_view(), name='home'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('change_post_status/<int:pk>/', change_post_status, name='change_post_status'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

# Create your models here.
NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):

    STATUSES = (
        ('active', 'активно'),
        ('moderation', 'модерация')
    )
    STATUS_ACTIVE = 'active'
    STATUS_MODERATION = 'moderation'

    header = models.CharField(max_length=50, verbose_name='Заголовок')
    content = models.CharField(max_length=900, verbose_name='Содержимое')
    image_preview = models.ImageField(upload_to='blog/', **NULLABLE, verbose_name='Изображение')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    publication_status = models.CharField(max_length=15, default=STATUS_MODERATION, choices=STATUSES, verbose_name='Статус публикации')
    number_of_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)


    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'публикации'

    def __str__(self):
        return f'{self.header}'

blog/forms.py
from blog.models import Blog
from mailing.forms_mixins import StyleFormMixin
from django import forms


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('header', 'content', 'image_preview', )

    def clean_header(self):
        header = self.cleaned_data['header']
        stop_word = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар', 'алкоголь', 'сигареты', 'табак']

        for word in stop_word:
            if word in header:
                raise forms.ValidationError('Данная тема противоречит политике сайта')

        return header

    def clean_content(self):
        content = self.cleaned_data['content']
        stop_word = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар', 'алкоголь', 'сигареты', 'табак']

        for word in stop_word:
            if word in content:
                raise forms.ValidationError('Контент содержит слова, противоречащие политике сайта')

        return content

blog/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from blog.forms import BlogForm
from blog.models import Blog
from blog.services import cache_home_page_all, random_publication


# Create your views here.
class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    ordering = ['-date_created']

class BlogCreateView(UserPassesTestMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(BlogCreateView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated

class BlogUpdateView(UserPassesTestMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:list')


    def test_func(self):
        post = self.get_object()
        if self.request.user.has_perm('blog.change_blog'):
            return True
        return self.request.user == post.owner

#
class BlogDetailView(UserPassesTestMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.number_of_views += 1
        obj.save()

        return obj

    def test_func(self):
        return self.request.user.is_authenticated

@permission_required(perm='blog.change_blog')
def change_post_status(request, pk):
    """Смена статуса поста"""
    obj = get_object_or_404(Blog, pk=pk)
    if obj.publication_status == Blog.STATUS_MODERATION:
        obj.publication_status = Blog.STATUS_ACTIVE
    else:
        obj.publication_status = Blog.STATUS_MODERATION
    obj.save()

    return redirect(request.META.get('HTTP_REFERER'))

class HomeListView(ListView):
    model = Blog
    template_name = 'mailing/home_page.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
#
        context_data['cache_home_page_all'] = cache_home_page_all()        
        context_data['cache_home_page'] = random_publication(context_data['cache_home_page_all'])

        return context_data

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}

{% block content %}

    <div class="container-xl">
        <div class="text-center">
            <img src="/media/{{ object.image_preview }}" height=300/>
            <br>
            <br>
            <div class="card-body text-center ">
                <h5 class="card-title">{{ object.header|capfirst }}</h5>
                <br>
                <br>
                <p class="text-center">{{ object.content|capfirst }}</p>

                {% if perms.blog.change_blog %}
                    <br>
                    <br>
                    <p class="text-center">Написал: {{ object.owner }}</p>
                {% endif %}
                {% if user == object.owner %}
                    <br>
                    <br>
                    <p class="text-center">Текущий статус: {{ object.get_publication_status_display|capfirst }}</p>


                    {% if object.publication_status == 'active' %}
                        <a class="text-danger-emphasis" href="{% url 'blog:change_post_status' object.pk %}">Убрать с
                            публикации</a>

                    {% endif %}
                {% endif %}
            </div>
        </div>
    <td><a class="p-2 btn btn-dark" href="{{ request.META.HTTP_REFERER|escape }}">Назад</a></td>
    </div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block client_create %}
    <div class="container-xl">
        <div class="text-center">
            <div class="col-4 ">
                <div class="card ">
                    <div class="card-body">
                    <form enctype="multipart/form-data" method="post" class="text-center">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="p-2 btn btn-dark" type="submit">Создать статью</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container-xl">
        <div class="text-center">
        <font size="4" color="#472929" face="sans-serif">

            <h1 class="display-4"> Шаматха </h1>

            {% for object in object_list %}
                {% if object.publication_status == "active" or perms.blog.change_blog or user == object.owner %}

                    <div class="card px-3 py-3 pt-md-5 pb-md-6 mx-auto text-center" style="width: 19rem;">
                        <img src="/media/{{ object.image_preview }}" height=140/>
                        <div class="card-body">
                            <h4 style="font-weight:bold">{{ object.header|capfirst }}</h4>
                            <p class="card-text">{{ object.content|slice:":80"|capfirst }}...</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Просмотров {{ object.number_of_views }}</li>
                            <li class="list-group-item">Создано {{ object.date_created|date }}</li>
                        </ul>

                        <ul class="list-unstyled text-small">
                            <li><a class="text-muted" href="{% url 'blog:detail' object.pk %}">Читать статью</a></li>
                            {% if perms.blog.change_blog or user == object.owner %}
                                <li><a class="text-warning-emphasis" href="{% url 'blog:update' object.pk %}">Обновить статью</a>
                                </li>
                            {% endif %}
                            {% if perms.blog.change_blog %}
                                <li>Текущий статус:
                                    {% if object.publication_status == 'moderation' %}
                                        <a class="text-danger-emphasis" href="{% url 'blog:change_post_status' object.pk %}">На
                                            модерации</a></li>
                                    {% else %}
                                        <a class="text-success" href="{% url 'blog:change_post_status' object.pk %}">Активна</a>
                                        </li>
                                    {% endif %}

                                </ul>
                            {% endif %}

                    </div>
                    <br>


                {% endif %}
            {% endfor %}
            <br>
            <br>


            <ul class="list-unstyled text-center ">
                <li><a class="p-2 btn btn-outline-dark px-3 mx-auto margin-top-10" href="{% url 'blog:create' %}">Создать
                    публикацию</a></li>
            </ul>
        </div>
    </div>

{% endblock %}