blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, change_post_status, HomeListView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('home/', HomeListView.as_view(), name='home'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('change_post_status/<int:pk>/', change_post_status, name='change_post_status'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    # path('', home, name='home'),
    # path('home2/', home2, name='home2'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('client/', ClientListView.as_view(), name='client'),
    path('settings/', SettingsListView.as_view(), name='settings'),
    path('create_settings/', SettingsCreateView.as_view(), name='create_settings'),
    path('update_settings/<int:pk>/', SettingsUpdateView.as_view(), name='update_settings'),
    path('delete_settings/<int:pk>/', SettingsDeleteView.as_view(), name='delete_settings'),
    path('detail_settings/<int:pk>/', SettingsDetailView.as_view(), name='detail_settings'),
    path('message/', MessageListView.as_view(), name='message'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('detail_message/<int:pk>/', MessageDetailView.as_view(), name='detail_message'),
    path('status/', Send_messageListView.as_view(), name='status'),
    path('delete_status/<int:pk>/', Send_messageDeleteView.as_view(), name='delete_status'),
    path('change_status_settings/<int:pk>/', change_status_settings, name='change_status_settings'),


]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import CustomLoginView, CustomRegisterView, UserEditProfileView, CustomPasswordChangeView, \
    activate_user, page_after_registration, CustomPasswordResetView, CustomPasswordResetConfirmView, \
    password_reset_send_mail, CustomPasswordResetCompleteView, UserListView, change_user_status

app_name = UsersConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(extra_context='/blog/home'), name='logout'),
    path('registration/', CustomRegisterView.as_view(), name='registration'),
    path('page_after_registration/<str:token>/', page_after_registration, name='page_after_registration'),
    path('profile/', UserEditProfileView.as_view(), name='profile'),
    path('password/', CustomPasswordChangeView.as_view(), name='password'), # пытался сделать урл change_password, но что-то как-то сложно...
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_send_mail/', password_reset_send_mail, name='password_reset_send_mail'),
    path('password_reset_complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password_reset_confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('activate/<str:token>/', activate_user, name='activate'),
    path('users_list/', UserListView.as_view(), name='users_list'),
    path('status/<int:pk>/', change_user_status, name='status'),
    # path('repeat_message/<str:token>/', repeat_message, name='repeat_message'),
    # path('reset_password/', ..., name='reset_password'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    username = None

    email = models.EmailField(verbose_name='почта', unique=True)
    phone = models.CharField(max_length=25, verbose_name='номер телефона', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=15, verbose_name='токен')
    token_time = models.DateTimeField(auto_now_add=True, verbose_name='время создания токена')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            (
                'change_status_user',
                'Can change the status user'
            ),


        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, ReadOnlyPasswordHashField, \
    PasswordChangeForm, PasswordResetForm, SetPasswordForm

from mailing.forms_mixins import StyleFormMixin
from users.models import User



class CustomAuthenticationForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = '__all__'


class CustomRegisterUserForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'avatar', 'phone', 'country')


class CustomEditUserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'phone', 'country')

class CustomPasswordChangeForm(StyleFormMixin, PasswordChangeForm):
    pass

class CustomPasswordResetForm(StyleFormMixin, PasswordResetForm):
    pass

class CustomSetPasswordForm(StyleFormMixin, SetPasswordForm):
    pass

users/views.py
import secrets

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView

from services.users_serv.confirm_account import confirm_account
from users.forms import CustomAuthenticationForm, CustomRegisterUserForm, CustomEditUserForm, CustomPasswordChangeForm, \
    CustomPasswordResetForm, CustomSetPasswordForm
from users.models import User


class CustomLoginView(LoginView):
    """Авторизация"""
    template_name = 'users/user_login.html'
    form_class = CustomAuthenticationForm
    model = User


class CustomRegisterView(CreateView):
    """Создать пользователя"""
    model = User
    form_class = CustomRegisterUserForm
    success_url = f'/users/page_after_registration/'


    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            self.object.is_active = False
            self.object.token = secrets.token_urlsafe(18)[:15]
            confirm_account(self.object)
            self.object.save()
            self.user_token = self.object.token
        return super().form_valid(form)

    def get_success_url(self):
        new_url = super().get_success_url()
        token = self.object.token
        return str(new_url) + str(token)



def page_after_registration(request, token):
    if request.method == 'POST':
        obj = get_object_or_404(User, token=token)
        confirm_account(obj)
    return render(request, 'users/page_after_registration.html')


class UserEditProfileView(UserPassesTestMixin, UpdateView):
    """Редактировать профиль"""
    model = User
    template_name = 'users/profile.html'
    form_class = CustomEditUserForm
    success_url = '/blog/home/'

    def get_object(self, queryset=None):
        return self.request.user

    def test_func(self):
        return self.request.user.is_authenticated

class CustomPasswordChangeView(UserPassesTestMixin, PasswordChangeView):
    """Смена пароля"""
    model = User
    success_url = '/blog/home/'
    form_class = CustomPasswordChangeForm
    template_name = 'users/change_password.html'

    def test_func(self):
        return self.request.user.is_authenticated

def activate_user(request, token):
    """Подтверждение профиля после регистрации"""
    u = User.objects.filter(token=token).first()

    if u:
        u.is_active = True
        u.save()
        return redirect('/users/login')

    return render(request, 'users/user_not_found.html')

class CustomPasswordResetView(PasswordResetView):
    """Смена пароля по почте (забыл пароль)"""
    template_name = 'users/password_reset.html'
    success_url = '/users/password_reset_send_mail'
    form_class = CustomPasswordResetForm
    email_template_name = 'users/email_reset.html'
    from_email = settings.EMAIL_HOST_USER



def password_reset_send_mail(request):
    """Смена пароля по почте (забыл пароль)"""
    return render(request, 'users/password_reset_send_mail.html')

class CustomPasswordResetConfirmView( PasswordResetConfirmView):
    """Смена пароля по почте (забыл пароль)"""
    template_name = 'users/reset_confirm.html'
    form_class = CustomSetPasswordForm
    success_url = reverse_lazy('users:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    """Смена пароля по почте (забыл пароль)"""
    template_name = 'users/password_reset_complete.html'


class UserListView(UserPassesTestMixin, ListView):
    """Просмотр списка зарегистрированных пользователей"""
    model = User
    template_name = 'users/user_list.html'

    def test_func(self):
        return self.request.user.has_perm("users.view_user")

@permission_required(perm='user.change_status_user')
def change_user_status(request, pk):
    """Смена статуса юзера"""
    obj = get_object_or_404(User, pk=pk)
    if obj.is_active:
        obj.is_active = False
    else:
        obj.is_active = True
    obj.save()

    return redirect(request.META.get('HTTP_REFERER'))

users/templates/users/change_password.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
        <form method="post" class="col-4">
            <div class="row">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="p-2 btn btn-dark" type="submit">Сохранить</button>
                            <td><a class="p-2 btn btn-dark" href="{{ request.META.HTTP_REFERER|escape }}">Назад</a></td>
                        </div>
                    </div>
                </div>
        </form>
    </div>

{% endblock %}

users/templates/users/email_reset.html
Запрошен сброс пароля на сайте "Спам и точка" для аккаунта {{ email }}.
Для обновления пароля перейдите по ссылке: {{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

users/templates/users/page_after_registration.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Спасибо за регистрацию!</h1>
        <br>
        <h5 class="display-8">Для подтверждения аккаунта, на почту была отправлена ссылка, перейдите по ней для
            завершения регистрации</h5>
        <form action="" method="post">
            {% csrf_token %}
            <input class="p-2 btn btn-dark" type="submit" name="upvote" value="Отправить повторно"/>
        </form>

    </div>

{% endblock %}

users/templates/users/password_reset.html
{% extends 'mailing/base.html' %}

{% block content %}

        <div class="container">
        <form method="post">
            <div class="row">
                <div class="col-5">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="p-2 btn btn-dark" type="submit">Сбросить пароль</button>
                            <td><a class="p-2 btn btn-dark" href="{{ request.META.HTTP_REFERER|escape }}">Назад</a></td>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Пароль успешно изменен</h1>
        <br>
        <td><a class="p-2 btn btn-dark" href="{% url 'users:login' %}">Вход</a></td>
    </div>

{% endblock %}

users/templates/users/password_reset_send_mail.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Запрос выполнен.</h1>
        <br>
        <h5 class="display-8">На почту отправлено сообщение. Для подтверждения сброса пароля перейдите по ссылке из сообщения</h5>
    </div>

{% endblock %}

users/templates/users/profile.html
{% extends 'mailing/base.html' %}

{% block content %}

        <div class="container">
        <form method="post">
            <div class="row">
                <div class="col-5">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="p-2 btn btn-dark" type="submit">Сохранить</button>
                            <td><a class="p-2 btn btn-dark" href="{{ request.META.HTTP_REFERER|escape }}">Назад</a></td>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/reset_confirm.html
{% extends 'mailing/base.html' %}

{% block content %}

        <div class="container">
        <form method="post">
            <div class="row">
                <div class="col-5">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            <h1 class="h3 mb-3 fw-normal">Введите новый пароль:</h1>
                            {{ form.as_p }}
                            <button class="p-2 btn btn-dark" type="submit">Сохранить пароль</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}

        <div class="container">
        <form method="post">
            <div class="row">
                <div class="col-5">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="p-2 btn btn-dark" type="submit">Сохранить</button>
                            <td><a class="p-2 btn btn-dark" href="{{ request.META.HTTP_REFERER|escape }}">Назад</a></td>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block client %}
    <div class="container-xl">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ФИО</th>
                <th scope="col">Email</th>
                <th scope="col">Номер телефона</th>
                <th scope="col">Страна</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    <th scope="row">{{ object.id }}</th>
                    <td>{{ object.last_name }} {{ object.first_name }}</td>
                    <td>{{ object.email }}</td>
                    <td>{{ object.phone }}</td>
                    <td>{{ object.country }}</td>
                    {% if object.is_active %}
                        <td><a class="btn btn-outline-success me-2" href="{% url 'users:status' object.pk %}">Активный</a></td>
                    {% else %}
                        <td><a class="btn btn-outline-danger me-2" href="{% url 'users:status' object.pk %}">Заблокированный</a></td>
                    {% endif %}


                </tr>
            {% endfor %}

            </tbody>
        </table>
        <td><a class="p-2 btn btn-dark" href="{% url 'mailing:create_client' %}">Добавить пользователя</a></td>
    </div>

{% endblock %}

users/templates/users/user_login.html
{% extends 'mailing/base.html' %}

{% block content %}
<main class="form-signin w-50 m-auto">

    <form method="post" class="col-6">
        <h1 class="h3 mb-3 fw-normal">Для авторизации введите данные:</h1>
        {% csrf_token %}
        {{ form.as_p }}

        <button class="w-100 btn btn-lg btn-dark" type="submit">Войти</button>
        <br>
        <br>
        <li><a class="text-muted" href="{% url 'users:password_reset' %}">Забыли пароль?</a></li>

        <p class="mt-5 mb-3 text-muted">&copy; 2017–2022</p>
    </form>
</main>

{% endblock %}

users/templates/users/user_not_found.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Возникла ошибка!</h1>
        <h1 class="display-8">Аккаунт не был найден.</h1>
        <br>
        <h5 class="display-8">Возможно прошло слишком много времени с момента регистрации, попробуйте повторно перейти по ссылке из сообщения или зарегистрироваться заново</h5>

        <a class="p-2 btn btn-outline-dark" href="{% url 'users:registration' %}">Рeгистрация</a>
    </div>

{% endblock %}