blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, change_post_status, HomeListView

app_name = BlogConfig.name

urlpatterns = [
    path('list/', BlogListView.as_view(), name='list'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('home/', HomeListView.as_view(), name='home'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('change_post_status/<int:pk>/', change_post_status, name='change_post_status'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    # path('', home, name='home'),
    # path('home2/', home2, name='home2'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('update_client/<int:pk>/', ClientUpdateView.as_view(), name='update_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('client/', ClientListView.as_view(), name='client'),
    path('settings/', SettingsListView.as_view(), name='settings'),
    path('create_settings/', SettingsCreateView.as_view(), name='create_settings'),
    path('update_settings/<int:pk>/', SettingsUpdateView.as_view(), name='update_settings'),
    path('delete_settings/<int:pk>/', SettingsDeleteView.as_view(), name='delete_settings'),
    path('detail_settings/<int:pk>/', SettingsDetailView.as_view(), name='detail_settings'),
    path('message/', MessageListView.as_view(), name='message'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('update_message/<int:pk>/', MessageUpdateView.as_view(), name='update_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('detail_message/<int:pk>/', MessageDetailView.as_view(), name='detail_message'),
    path('status/', Send_messageListView.as_view(), name='status'),
    path('delete_status/<int:pk>/', Send_messageDeleteView.as_view(), name='delete_status'),
    path('change_status_settings/<int:pk>/', change_status_settings, name='change_status_settings'),


]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}

class Client(models.Model):

    email = models.EmailField(max_length=60, verbose_name='Email')
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(blank=True, verbose_name='Комментарий')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'

    def __str__(self):
        return f'{self.email} {self.fio}'


class Message(models.Model):

    title = models.CharField(max_length=80, verbose_name='Тема письма')
    text = models.TextField(verbose_name='Тело письма')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    class Meta:
        verbose_name = 'письмо'
        verbose_name_plural = 'письма'

    def __str__(self):
        return f'{self.title}'


class Settings(models.Model):
    FREQUENCY = (
        ('day', 'раз в день'),
        ('week', 'раз в неделю'),
        ('month', 'раз в месяц'),
    )
    FREQUENCY_DAY = 'day'
    FREQUENCY_WEEK = 'week'
    FREQUENCY_MONTH = 'month'

    STATUS = (
        ('completed', 'завершена'),
        ('created', 'создана'),
        ('launched', 'запущена'),
    )
    STATUS_COMPLETED = 'completed'
    STATUS_CREATED = 'created'
    STATUS_LAUNCHED = 'launched'

    mailing_time = models.TimeField(verbose_name='Время рассылки')
    frequency = models.CharField(max_length=25, default=FREQUENCY_DAY, choices=FREQUENCY, verbose_name='Периодичность')
    status = models.CharField(max_length=25, default=STATUS_CREATED, choices=STATUS, verbose_name='Статус')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Сообщение')

    addressee = models.ManyToManyField(Client, verbose_name='Адреса')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)

    class Meta:
        verbose_name = 'настройки'
        verbose_name_plural = 'настройки'

        permissions = [
            (
                'change_status_settings',
                'Can change the status settings'
            ),

        ]

    def __str__(self):
        return f'{self.mailing_time}, {self.frequency}'


class Send_message(models.Model):
    STATUS = (
        ('delivered', 'доставлено'),
        ('not_delivered', 'не доставлено'),
    )
    STATUS_DELIVERED = 'delivered'
    STATUS_NOT_DELIVERED = 'not_delivered'

    sending_time = models.DateTimeField(verbose_name='Время рассылки')
    status = models.CharField(max_length=25, default=STATUS_DELIVERED, choices=STATUS, verbose_name='Статус')
    server_response = models.CharField(blank=True, max_length=100, verbose_name='Ответ сервера')

    settings_pk = models.ForeignKey(Settings, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)


    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытка рассылки'

    def __str__(self):
        return f'{self.sending_time} {self.status} {self.server_response} '

mailing/forms.py
from django import forms

from mailing.forms_mixins import StyleFormMixin
from mailing.models import Client, Message, Settings


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        exclude = ('owner',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ('title', 'text',)
        exclude = ('owner',)


class SettingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Settings
        fields = ('mailing_time', 'frequency', 'status', 'message', 'addressee')
        exclude = ('owner',)

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop('owner')
        super().__init__(*args, **kwargs)

        self.fields['addressee'].queryset = Client.objects.filter(owner=owner)
        self.fields['message'].queryset = Message.objects.filter(owner=owner)

mailing/views.py
import random

from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import *

from blog.models import Blog
from mailing.forms import ClientForm, MessageForm, SettingsForm
from mailing.models import *
from django.urls import reverse_lazy

# def home(request):
#     blog = Blog.objects.filter(publication_status=Blog.STATUS_ACTIVE)
#     blog_id = [item[0] for item in blog.values_list('id')]
#     random.shuffle(blog_id)
#     number_publication = 3
#
#     if len(blog_id) < 3:
#         number_publication = len(blog_id)
#
#     return render(request, 'mailing/home_page.html', {'blog':[blog.filter(id=blog_id[n]) for n in range(number_publication)]})


class ClientListView(UserPassesTestMixin, ListView):
    model = Client
    template_name = 'mailing/client/client_list.html'

    def test_func(self):
        return self.request.user.is_authenticated



class ClientCreateView(UserPassesTestMixin, CreateView):
    model = Client
    success_url = reverse_lazy('mailing:client')
    template_name = 'mailing/client/client_form.html'
    form_class = ClientForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(ClientCreateView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated

class ClientUpdateView(UserPassesTestMixin, UpdateView):
    model = Client
    success_url = reverse_lazy('mailing:client')
    template_name = 'mailing/client/client_form.html'
    form_class = ClientForm

    def test_func(self):
        client = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == client.owner

class ClientDeleteView(UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client')
    template_name = 'mailing/client/client_confirm_delete.html'

    def test_func(self):
        client = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == client.owner


class SettingsListView(UserPassesTestMixin, ListView):
    model = Settings
    template_name = 'mailing/settings/settings_list.html'

    def test_func(self):
        return self.request.user.is_authenticated

class SettingsCreateView(UserPassesTestMixin, CreateView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_form.html'
    form_class = SettingsForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(SettingsCreateView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'owner':self.request.user})
        return kwargs

class SettingsUpdateView(UserPassesTestMixin, UpdateView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_form.html'
    form_class = SettingsForm

    def test_func(self):
        settings = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == settings.owner

class SettingsDeleteView(UserPassesTestMixin, DeleteView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_confirm_delete.html'

    def test_func(self):
        settings = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == settings.owner

class SettingsDetailView(UserPassesTestMixin, DetailView):
    model = Settings
    success_url = reverse_lazy('mailing:settings')
    template_name = 'mailing/settings/settings_detail.html'

    def test_func(self):
        message = self.get_object()
        if self.request.user == message.owner:
            return True
        return self.request.user.has_perm('mailing.view_settings')


class MessageListView(UserPassesTestMixin, ListView):
    model = Message
    template_name = 'mailing/message/message_list.html'

    def test_func(self):
        return self.request.user.is_authenticated

class MessageCreateView(UserPassesTestMixin, CreateView):
    model = Message
    success_url = reverse_lazy('mailing:message')
    template_name = 'mailing/message/message_form.html'
    form_class = MessageForm

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.owner = self.request.user
            self.object.save()
        return super(MessageCreateView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated

class MessageUpdateView(UserPassesTestMixin, UpdateView):
    model = Message
    success_url = reverse_lazy('mailing:message')
    template_name = 'mailing/message/message_form.html'
    form_class = MessageForm

    def test_func(self):
        message = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == message.owner

class MessageDeleteView(UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message')
    template_name = 'mailing/message/message_confirm_delete.html'

    def test_func(self):
        message = self.get_object()
        if self.request.user.is_superuser:
            return True
        return self.request.user == message.owner

class MessageDetailView(UserPassesTestMixin, DetailView):
    model = Message
    template_name = 'mailing/message/message_detail.html'

    def test_func(self):
        message = self.get_object()
        if self.request.user == message.owner:
            return True
        return self.request.user.has_perm('mailing.view_message')


class Send_messageListView(UserPassesTestMixin, ListView):
    model = Send_message
    template_name = 'mailing/send/send_message_list.html'

    def test_func(self):
        return self.request.user.is_authenticated

class Send_messageDeleteView(UserPassesTestMixin, DeleteView):
    model = Send_message
    success_url = reverse_lazy('mailing:status')
    template_name = 'mailing/send/send_message_confirm_delete.html'

    def test_func(self):
        return self.request.user.is_superuser


def change_status_settings(request, pk):
    """Смена статуса настройки"""
    obj = get_object_or_404(Settings, pk=pk)
    if obj.status == Settings.STATUS_COMPLETED or obj.status == Settings.STATUS_CREATED:
        obj.status = Settings.STATUS_LAUNCHED
    elif obj.status == Settings.STATUS_LAUNCHED:
        obj.status = Settings.STATUS_COMPLETED
    obj.save()

    return redirect(request.META.get('HTTP_REFERER'))

mailing/templates/mailing/settings/settings_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block client_delete %}
    <div class="container-xl">
        <br>
        <br>
        <div class="col-5">
            <div class="text-center">
                <div class="card ">
                    <div class="card-body">
                        <form enctype="multipart/form-data" method="post" class="text-center">
                            {% csrf_token %}
                            <p>
                                Удалить настройку с частотой {{ object.frequency }} в {{ object.mailing_time }}?
                            </p>
                            <a class="text-muted" href="{% url 'mailing:settings' %}">Отменить</a>
                            <button class="p-2 btn btn-dark" type="submit">Удалить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

mailing/templates/mailing/settings/settings_detail.html
{% extends 'mailing/base.html' %}

{% block detail_settings%}
    <div class="container-xl">
        <br>
        <br>

        <p class="h2">{{ object.message.title }}</p>
        <p>
            <br>
        </p>
        <p>{{ object.message.text }}</p>
        <br>
        <br>
        <p>Периодичность:   {{ object.get_frequency_display }} </p>
        <p>Статус:   {{ object.get_status_display }} </p>
        <p>Адреса получателей: {% for address in object.addressee.all %}
                        < {{ address.email }} >
                        {% endfor %} </p>

         {% if perms.mailing.view_settings %}
           Пользователь: {{ object.owner }}
        {% endif %}
           <br>
        <br>

        <td><a class="p-2 btn btn-dark" href="{% url 'mailing:settings' %}">Назад</a></td>

    </div>

{% endblock %}

mailing/templates/mailing/settings/settings_form.html
{% extends 'mailing/base.html' %}

{% block settings_create %}
    <div class="container-xl">
        <div class="text-center">
            <div class="col-4 ">
                <div class="card ">
                    <div class="card-body">
                        <form enctype="multipart/form-data" method="post" class="text-center">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="p-2 btn btn-dark" type="submit">Завершить настройку</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

mailing/templates/mailing/settings/settings_list.html
{% extends 'mailing/base.html' %}

{% block settings %}
    <div class="container-xl">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Время рассылки</th>
                <th scope="col">Периодичность</th>
                <th scope="col">Статус</th>
                <th scope="col">Сообщение</th>
                <th scope="col">Адреса рассылки</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
                <tr>
                    {% if user == object.owner or perms.mailing.view_settings %}
                        <th scope="row">{{ object.id }}</th>
                        <td>{{ object.mailing_time }}</td>
                        <td>{{ object.get_frequency_display }}</td>
                        {% if user == object.owner or perms.mailing.change_status_settings %}
                            {% if object.get_status_display == 'завершена' %}
                                <td><a class="btn btn-outline-danger me-2"
                                       href="{% url 'mailing:change_status_settings' object.pk %}">Не
                                    активна</a></td>
                            {% else %}
                                <td><a class="btn btn-outline-success me-2"
                                       href="{% url 'mailing:change_status_settings' object.pk %}">Активна</a>
                                </td>
                            {% endif %}
                        {% else %}
                            {{ object.get_status_display }}
                        {% endif %}
                        <td>{{ object.message.title }}</td>
                        <td>{% for address in object.addressee.all %}
                            {{ address.email }}<br>
                        {% endfor %}
                        </td>
                        <td><a class="text-black" href="{% url 'mailing:detail_settings' object.pk %}">Подробнее</a>
                        </td>
                        {% if user == object.owner or user.is_superuser %}
                            <td><a class="text-black" href="{% url 'mailing:update_settings' object.pk %}">Изменить</a>
                            </td>
                            <td><a class="text-black" href="{% url 'mailing:delete_settings' object.pk %}">Удалить</a>
                            </td>
                        {% endif %}
                    {% endif %}
                </tr>
            {% endfor %}

            </tbody>
        </table>
        <td><a class="p-2 btn btn-dark" href="{% url 'mailing:create_settings' %}">Создать новую рассылку</a></td>
        <br>
        <br>
        <td><a class="p-2 btn btn-dark" href="{% url 'mailing:message' %}">Назад</a></td>
    </div>

{% endblock %}